const ENTITIES = require('html-entities').AllHtmlEntities;
const URL = require('url');
const QUERYSTRING = require('query-string');
const BASE_URL = 'https://www.youtube.com/results?';

// Builds the search query url
const buildLink = query => BASE_URL + QUERYSTRING
  .encode({
    search_query: query,
    spf: 'navigate',
    gl: 'US',
    hl: 'en',
  });

const buildFromNextpage = nextpageRef => {
  let parsed = URL.parse(nextpageRef, true);
  let overwrites = QUERYSTRING.decode(parsed.search.substr(1));
  return BASE_URL + QUERYSTRING.encode(Object.assign({}, overwrites, {
    spf: 'navigate',
    gl: 'US',
    hl: 'en',
  }));
};

// Start of parsing an item
const parseItem = (string, respString, searchString) => {
  const titles = this.between(string, '<div class="', '"');
  const type = this.between(titles, 'yt-lockup yt-lockup-tile yt-lockup-', ' ');
  if (type === 'playlist') {
    if (string.includes('yt-pl-icon-mix')) return this.parseMix(string);
    return this.parsePlaylist(string);
  } else if (type === 'channel') {
    return this.parseChannel(string);
  } else if (type === 'video') {
    return this.parseVideo(string);
  } else if (type === 'movie-vertical-poster') {
    return this.parseMovie(string);
  } else if (titles === 'search-refinements') {
    return this.parseRelatedSearches(string);
  } else if (titles.includes('shelf') && string.includes('<div class="compact-shelf')) {
    return this.parseShelfCompact(string);
  } else if (titles.includes('shelf') && string.includes('<div class="vertical-shelf">')) {
    return this.parseShelfVertical(string);
  } else if (string.includes('<div class="display-message">No more results</div>')) {
    return null;
  } else {
    return null;
  }
};

const parseMix = string => {
  const thumbnailRaw = this.between(string, 'data-thumb="', '"');
  const thumbnail = thumbnailRaw ? thumbnailRaw : this.between(string, 'src="', '"');
  const plistID = this.removeHtml(this.between(string, 'data-list-id="', '"'));
  const videoID = this.removeHtml(this.between(string, 'data-video-ids="', '"'));
  return {
    type: 'mix',
    title: this.removeHtml(this.between(this.between(string, '<h3 class="yt-lockup-title ">', '</a>'), '>')),
    firstItem: `https://www.youtube.com/watch?v=${videoID}&list=${plistID}`,
    thumbnail: URL.resolve(BASE_URL, this.removeHtml(thumbnail)),
    length: this.removeHtml(this.between(string, '<span class="formatted-video-count-label">', '</span>')),
  };
};

// Parse an item of type playlist
const parsePlaylist = string => {
  const ownerBox = this.between(string, '<div class="yt-lockup-byline ">', '</div>');
  const thumbnailRaw = this.between(string, 'data-thumb="', '"');
  const thumbnail = thumbnailRaw ? thumbnailRaw : this.between(string, 'src="', '"');
  const cleanID = this.removeHtml(this.between(string, 'data-list-id="', '"'));
  return {
    type: 'playlist',
    title: this.removeHtml(this.between(this.between(string, '<h3 class="yt-lockup-title ">', '</a>'), '>')),
    link: `https://www.youtube.com/playlist?list=${cleanID}`,
    thumbnail: URL.resolve(BASE_URL, this.removeHtml(thumbnail)),

    author: {
      name: this.removeHtml(this.between(ownerBox, '>', '</a>')),
      ref: URL.resolve(BASE_URL, this.removeHtml(this.between(ownerBox, '<a href="', '"'))),
      verified: string.includes('title="Verified"'),
    },

    length: this.removeHtml(this.between(string, '<span class="formatted-video-count-label">', '</span>')),
  };
};

// Parse an item of type channel
const parseChannel = string => {
  const avatarRaw = this.between(string, 'data-thumb="', '"');
  const avatar = avatarRaw ? avatarRaw : this.between(string, 'src="', '"');
  const rawDesc = this.between(this.between(string, '<div class="yt-lockup-description', '</div>'), '>');
  const rawFollows = this.between(this.between(string, 'yt-subscriber-count"', '</span>'), '>');
  return {
    type: 'channel',
    name: this.removeHtml(this.between(this.between(string, '<a href="', '</a>'), '>')),
    channel_id: this.between(string, 'data-channel-external-id="', '"'),
    link: URL.resolve(BASE_URL, this.removeHtml(this.between(string, 'href="', '"'))),
    avatar: URL.resolve(BASE_URL, this.removeHtml(avatar)),
    verified: string.includes('title="Verified"') || string.includes('yt-channel-title-autogenerated'),

    followers: Number(rawFollows.replace(/\.|,/g, '')),
    description_short: this.removeHtml(rawDesc) || null,
    videos: Number(this.between(string, '<ul class="yt-lockup-meta-info"><li>', '</li>')
      .split(' ')
      .splice(0, 1)[0]
      .replace(/\.|,/g, '')
    ),
  };
};

// Parse an item of type video
const parseVideo = string => {
  const ownerBox = this.between(string, '<div class="yt-lockup-byline ">', '</div>');
  const metaInfo = this.between(string, '<div class="yt-lockup-meta ">', '</ul>')
    .replace(/<\/li>/g, '')
    .split('<li>')
    .splice(1);
  const thumbnailRaw = this.between(string, 'data-thumb="', '"');
  const thumbnail = thumbnailRaw ? thumbnailRaw : this.between(string, 'src="', '"');
  const rawDesc = this.between(this.between(string, '<div class="yt-lockup-description', '</div>'), '>');
  return {
    type: 'video',
    title: this.removeHtml(this.between(this.between(string, '<a href="', '</a>'), '>')),
    link: URL.resolve(BASE_URL, this.removeHtml(this.between(string, 'href="', '"'))),
    thumbnail: URL.resolve(BASE_URL, this.removeHtml(thumbnail)),

    author: {
      name: this.removeHtml(this.between(ownerBox, '>', '</a>')),
      ref: URL.resolve(BASE_URL, this.removeHtml(this.between(ownerBox, '<a href="', '"'))),
      verified: ownerBox.includes('title="Verified"'),
    },

    description: this.removeHtml(rawDesc) || null,
    views: metaInfo[1] ? Number(metaInfo[1].split(' ')[0].replace(/\.|,/g, '')) : null,
    duration: this.between(string, '<span class="video-time" aria-hidden="true">', '</span>'),
    uploaded_at: metaInfo[0] || null,
  };
};

// Parse am item of type movie
const parseMovie = string => {
  const haystack = string.substr(string.lastIndexOf('<div class="yt-lockup-meta"><ul>') + 32);
  const filmMeta = haystack.substr(0, haystack.indexOf('</ul></div>'));
  const authorInfo = `${string.substr(string.lastIndexOf('<a'), string.lastIndexOf('</a>'))}</a>`;
  const rawDesc = this.between(string, 'yt-lockup-description', '</div>').replace(/[^>]+>/, '');
  const rawMeta = this.between(string, '<div class="yt-lockup-meta"><ul><li>', '</li></ul>');
  return {
    type: 'movie',
    title: this.removeHtml(this.between(string, 'dir="ltr">', '</a>')),
    link: URL.resolve(BASE_URL, this.removeHtml(this.between(string, 'href="', '"'))),
    thumbnail: URL.resolve(BASE_URL, this.removeHtml(this.between(string, 'src="', '"'))),

    author: {
      name: this.removeHtml(this.between(authorInfo, '>', '<')),
      ref: URL.resolve(BASE_URL, this.removeHtml(this.between(authorInfo, '<a href="', '"'))),
      verified: string.includes('title="Verified"'),
    },

    description: this.removeHtml(rawDesc) || null,
    meta: this.removeHtml(rawMeta).split(' · '),
    actors: filmMeta.split('<li>')[1].replace(/<[^>]+>|^[^:]+: /g, '').split(', ').map(a => this.removeHtml(a)),
    director: this.removeHtml(filmMeta.split('<li>')[2].replace(/<[^>]+>|^[^:]+: /g, '')),
    duration: this.between(string, '<span class="video-time" aria-hidden="true">', '</span>'),
  };
};

// Parse an item of type related searches
const parseRelatedSearches = string => {
  const related = string.split('search-refinement').splice(2);
  return {
    type: 'search-refinements',
    entrys: related.map(item => ({
      link: URL.resolve(BASE_URL, this.removeHtml(this.between(item, 'href="', '"'))),
      q: QUERYSTRING.parse(this.removeHtml(this.between(item, '/results?', '"'))).search_query || null,
    })),
  };
};

// Horizontal shelf of youtube movie proposals
const parseShelfCompact = string => {
  const itemsRaw = string.split('<li class="yt-uix-shelfslider-item').splice(1);
  const items = itemsRaw.map(item => ({
    type: `${this.between(item, ' ', '-')}-short`,
    name: this.removeHtml(this.between(this.between(item, '><a href="', '</a>'), '>', '')),
    ref: URL.resolve(BASE_URL, this.removeHtml(this.between(item, 'href="', '"'))),
    thumbnail: URL.resolve(BASE_URL, this.removeHtml(this.between(item, 'src="', '"'))),
    duration: this.between(item, '"video-time"', '<').replace(/^[^>]+>/, ''),
    price: this.between(item, '<span class="button-label">', '</span>').replace(/^[^ ]+ /, '') || null,
  }));
  return {
    type: 'shelf-compact',
    title: this.removeHtml(this.between(string, '<span class="branded-page-module-title-text">', '</span>')),
    items,
  };
};

// Vertical shelf of youtube video proposals
const parseShelfVertical = string => {
  const itemsRaw = string.split('<a aria-hidden="').splice(1);
  return {
    type: 'shelf-vertical',
    title: this.removeHtml(this.between(string, '<span class="branded-page-module-title-text">', '</span>')),
    items: itemsRaw.map(item => this.parseVideo(item)),
  };
};

// Taken from https://github.com/fent/node-ytdl-core/
const between = this.between = (haystack, left, right) => {
  let pos;
  pos = haystack.indexOf(left);
  if (pos === -1) { return ''; }
  haystack = haystack.slice(pos + left.length);
  if (!right) { return haystack; }
  pos = haystack.indexOf(right);
  if (pos === -1) { return ''; }
  haystack = haystack.slice(0, pos);
  return haystack;
};

// Cleans up html text
const removeHtml = this.removeHtml = string => new ENTITIES().decode(
  string.replace(/\n/g, ' ')
    .replace(/\s*<\s*br\s*\/?\s*>\s*/gi, '\n')
    .replace(/<\s*\/\s*p\s*>\s*<\s*p[^>]*>/gi, '\n')
    .replace(/<.*?>/gi, '')
).trim();

const getPage = (ref, cb) => {
    fetch(ref)
    .then((response) => response.text())
    .then((resp) => {
        cb(null, resp);
    })
    .catch((err) => "Error:", cb)
};

const parseFilters = body => {
  const filterContainer = between(body, '<div id="filter-dropdown"', '<ol id="item-section');
  const coloms = filterContainer.split('<h4 class="filter-col-title">').splice(1);
  const results = new Map();
  coloms.forEach(c => {
    const items = c.trim().split('<li>').filter(a => a);
    const title = between(items.splice(0, 1)[0], '', '</h4>');
    const array = results.set(title, []).get(title);
    array.active = null;
    items.forEach(i => {
      let isActive = between(i, 'class="', '"').includes('filter-selected');
      let parsedItem = {
        ref: isActive ? null : URL.resolve(BASE_URL, removeHtml(between(i, 'href="', '"'))),
        name: removeHtml(between(between(i, '>', '</span>'), '>')),
        active: isActive,
      };
      if (isActive) array.active = parsedItem;
      array.push(parsedItem);
    });
  });
  return results;
};
